### ISSUE TITLE
Mehr Zeilen Anzeigen können

### ISSUE THREAD

**Issue by Noggle70** [Achimobil/FS22_ProductionInfoHud#11]
Hallo, 
vielen Dank für diese Gameplay Erweiterung. 
Habe eine Frage dazu..
Kann man die Produktion Info HUD Anzeige vielleicht auf 20-25 Zeilen erhöhen ?

Grüßlies

**Comment by Achimobil** [comment]
Das Problem ist, dass es an ein und der gleichen Stelle viele Anzeigen gleichzeitig gibt und es bei zu vielen Zeilen dann zum overflow kommt wo man nicht mehr alles sehen kann. Allerdings erhöh mein mod die Anzahl der Zeilen ja schon auf 25 beim Silo. Produktionen sollten nicht so viele Zeilen haben

**Comment by Noggle70** [comment]
Durch die PlanET BGA habe ich zig Produktionen, die meissten davon sind dann immer voll, also rot.. 
Schade, aber wenns nicht geht, dann gehts halt nicht :)
Trotzdem vielen dank.. 
Eine Frage noch.. Kann man selektieren, was im HUD angezeigt werden soll ?

Grüßlies

**Comment by Achimobil** [comment]
Mach doch mal einen Screenshot damit ich sehe wie und wo du das genau meinst und schau doch mal hier, Ich hab die zwar nicht mit den PnH fermentern getestet, sollte aber gehen: https://youtu.be/sMYGojFF-w8

**Comment by Achimobil** [comment]
Stop Sorry, ich hab die beiden mods mal wieder verwechselt.

Ja, es wäre möglich mehr Zeilen mit einem Update ein zu fügen, aber das wird dann auch sehr schnell unübersichtlich.
Ich würde empfehlen dass du dir mal die Kombination aus PIH und Multi Overly Hud anschaust, da werden nämlich alle angezeigt in einer Scrollbaren Liste deren Position und größe du selbst anpassen kannst.
Ich hab das hier im Video mal gezeigt: https://youtu.be/QqqHrFypVWY

**Comment by Noggle70** [comment]
Mit dem Video kann ich leider nichts anfangen.. 

Aber ich sende mal einen Screenshot mit.. 

![PRODINFHUD](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/86755520/ace2be59-79f2-4cca-ba02-c5b7032490eb)

**Comment by Achimobil** [comment]
Also ich würde erst mal vorschlagen die Vollen produktionen ab zu schalten. Zusätzliche eine Heizkraftwerk mehr bauen, den es ist  eigentlich das Ziel allles dirket zu verbrauchen bei den PnH BGAs. Den Input der Heizkraftwerke kann man im Produktionsmenü dann auf ignorieren stellen.

**Comment by Noggle70** [comment]
Das mit dem Rohmethan ist so eine Sache.. 
Ich weiß nicht, ob das nur bei mir so ist..
Meine Rohmethanlager sind ständig voll, aber die Elektroproduktionen, und das Methanlager immer fast leer. 
Irgendwie scheint das mit dem Verteilen nicht ganz zu klappen. 
Ich hab bei Revamp die Prioritäten überall auf 1 gesetzt. 
Das war auch eigentlich der Hintergrund meiner Frage, ob man Zeilen hinzufügen könnte. 
Da das Methanlager sehr selten angezeigt wird, und die Stromproduktionen nie.. 
Ich könnte zwar auch immer wieder ins Revamp Menü gehen und nachschauen, aber der Info HUD ist ne klasse Sache und der Mensch ist von Natur aus faul :)

Grüßlies

**Comment by Achimobil** [comment]
Also zum verteilen kann ich so nichts sagen, warum das nicht so geht wie es soll. Bei einem Lager kann ja nichts verteilt werden somit muss das ja auch eine Produktion sein. Aber da wendest du sich besser mal an den Modder der BGA oder im Revamp Discord mal alle Details posten wegen der Verteilung. Bei den PnH BGA's funktioniert das verteilen, das weiß ich.

Mit dem Multi Overlay Hud, der mein Hud in einem Fenster anzeigen kann werden alle Zeilen angezeigt und somit hast du da mehr Möglichkeiten. Du solltest dir das genauer anschauen.

Ich nehme mehr Zeilen einstellbar mal als Wunsch für kommende Version mit.

**Comment by Noggle70** [comment]
Vielen Dank für die Vorabversion 1.3.0.0 
gleich getestet und für sehr gut befunden :):)

Danke nochmal

**Comment by Achimobil** [comment]
Gern geschehen, war wenig Aufwand wie ich das gemacht habe, deshalb auch so schnell ;)
