### ISSUE TITLE
Versteckte Revamp Produktionen nicht anzeigen

### ISSUE THREAD

**Issue by Holger-70** [Achimobil/FS22_ProductionInfoHud#13]
Es wäre schön wenn Revamp-Produktionen die in der Produktions-Menü nicht angezeigt werden auch in den Produktions-Infohud nicht angezeigt werden.

**Comment by Achimobil** [comment]
@Holger-70 Hast du da ein Beispiel welche Produktion versteckt sein sollte aber angezeigt wird?

**Comment by Holger-70** [comment]
@Achimobil auf der Canyon Crossing  sind das die Baustellen für die Brücken, Baustellen für Produktionsgebäude fest verbaut und auch plazierbare und jede Menge Objektspawner wleche man mit Kauf des Grundstücks erwirbt und je nach Jahreszeit Objekt(Paletten) aus Regen produziert werden.

**Comment by Achimobil** [comment]
Im Modhub hab ich die nicht gefunden, haste mal nen link?

**Comment by Holger-70** [comment]
ist auch nicht im Modhub schicke dir im Discord einen Link von meinen Server

**Comment by Achimobil** [comment]
Link zur Karte: https://trello.com/b/ZdyWgZme/mods-by-dajnet

**Comment by Achimobil** [comment]
5Gb mit 130 eigenen mods. Dafür werde ich garantiert keine Testumbegung aufsetzen nur um das zu testen.
Ich werde etwas einbauen dass funktionieren könnte und dann kannst du das selbst testen. 
Ansonsten: ModHub Map bitte, die das benutzt und wo ich das Testen kann.

**Comment by Achimobil** [comment]
Schau mal in https://github.com/Achimobil/FS22_ProductionInfoHud/releases/tag/1.3.0.4, ob es damit Funktioniert bitte und gib mir eine Rückmeldung.

**Comment by Achimobil** [comment]
Da testet man ein mal nicht direkt und schon ein typo in der lua. bitt mit der Version testen: https://github.com/Achimobil/FS22_ProductionInfoHud/releases/tag/1.3.0.5

**Comment by Holger-70** [comment]
![fsScreen_2023_10_26_18_04_30](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/142307444/f5a7861a-5bb3-47c4-853f-499d997d925b)
werden leider immer noch angezeigt
Gruß Holger

**Comment by Achimobil** [comment]
Also generell will ich für die Map kein eigenes PRofil anlegen, ist viel zu aufwändig und einen Mod der das hat hab ich nicht gefunden. Aber ich hab gesehen dass ich nur in der Produktionübersicht ausgebledet habe und habe das jetzt für die 1.3.0.6 angepasst. Die schick ich gleich hoch und dann kannst du damit noch mal schauen

**Comment by Holger-70** [comment]
habe keine Nachricht oder wo muss ich da schauen

**Comment by Holger-70** [comment]
gefunden habe es über die Hauptseite geladen, auf den ersten Blick sieht alles gut aus die ganzen nicht sichtbaren sind aus der Anzeige verschwunden werde weiter testen ich melde mich

**Comment by Holger-70** [comment]
Alle Produktionen bzw. Produktionslinien die in den LS22 Produktionsmenü nicht sichtbar sind werden auch im ProductionInfoHud nicht angezeigt. Was aber angezeigt wird sind die Rohstoffe welche zum Bau eines Gebäudes benötig werden aber auch nur die die nicht zum späteren Produktionprozess egal ob Rohstoff oder Produkt gehören. Bild-1 Block,Paver und Concrete wird nicht angezeigt weil es ja da später produziert werden kann, im Produktionsverlauf kommt natürlich die Anzeige korrekt wenn das Produkt voll ist. Bild-2 wird natürlich nichts angezeigt so lange die Produktion (Bau des Gebäudes) läuft. Bild-3 nach Bauabschluss werden wieder die Rohstoffe als leer angezeigt.  
![Übersicht](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/142307444/a71774fb-01e6-42ea-a85b-f781e7c3bc0a)

**Comment by Achimobil** [comment]
Dann muss da noch irgendwas sein ,ich habe die bei mir in meiner test produktion ausgeblendet über hideFromMenu und egal ob die voll oder leer sind, sie sind immer ausgeblendet, weil sobald eine Linie das aktiviert hat, wird alles ausgeblendet davon. Ich konnte auch nichts in Revamp finden, was da was anders macht.
@braeven kannst du dir da noch einen Reim drauf machen? Ansonsten kann ich hier einfach nichts mehr entdecken und dann müsste es an anderen skripten liegen, aber auf der Map debugge ich das bestimmt nicht

**Comment by braeven** [comment]
Da werden nur Revamp-Funktionalitäten genutzt, insbesondere die ObjectFillLevel.

Die Produktion wird über eine Produktionslinie gebaut, die die Rohstoffe Stückweise in einen Hilfs-Filltype umwandelt, über den dann die einzelnen Gebäudeteile sichtbar werden und der Zaun ausgeblendet wird.

ObjectFillLevel
`		<ProductionObjectFillLevels useSubNodesInsteadOfMainNodes="true">						
			<ProductionObjectFillLevel fillType="CONCRETEBUILD2" 	rootNode="fence" 			maxAtFillLevel="9950" firstAtFillLevel="9950" invert="true"/>
			<ProductionObjectFillLevel fillType="CONCRETEBUILD2" 	rootNode="concretebuild" 	maxAtFillLevel="9950"/>
        </ProductionObjectFillLevels>`

Produktionslinie:
`			<production id="ConcreteBuilder" name="Concrete Contruction" cyclesPerHour="8" costsPerActiveHour="1" hideFromMenu="true">
                <inputs>                   
					<input fillType="BLOCK" 			amount="1000" />	
					<input fillType="GLASS" 			amount="250" />					
					<input fillType="DRYWALL" 			amount="250" />	
					<input fillType="PAVER" 			amount="250" />					
					<input fillType="SHINGLE" 			amount="500" />	
					<input fillType="STAIRCASERAILING" 	amount="250" />	
					<input fillType="FABRIC" 			amount="250" />	
					<input fillType="METAL" 			amount="250" />
					<input fillType="FLOORTILES" 		amount="500" />	
					<input fillType="CONCRETE" 			amount="500" />	
                </inputs>
                <outputs>
                    <output fillType="CONCRETEBUILD2" 			amount="100" />					
                </outputs>
            </production>`

Die läuft natürlich irgendwann leer, wenn die Produktion fertig gebaut ist, was dein Infohud scheinbar wieder aufgreift.

Die Capacities der Rohstoffe sind auch in der ProduktionsÜbersicht ausgeblendet:
`<capacity fillType="DRYWALL"     		capacity="25000" hideFromMenu="true"/>`

**Comment by Achimobil** [comment]
Aber mit dem folgenden code sollte das doch dann immer ausgeblendet sein. Zumindest in meinem Test mit meiner Produktion klappt das auch problemlos:

```lua
			-- hidden stuff from revamp production script
			for i = 1, #productionPoint.activeProductions do
				local activeProduction = productionPoint.activeProductions[i];
				
				if activeProduction.hideComplete ~= nil and activeProduction.hideComplete == true then
					goto ignoreProduction
				end
			end
```

**Comment by Achimobil** [comment]
@Holger-70 versuch es noch mal mit der neuen Version, ich hab das noch mal komplett überarbeitet
https://github.com/Achimobil/FS22_ProductionInfoHud/releases/tag/1.3.0.9

**Comment by Holger-70** [comment]
die Anzeige der leeren Rohstoffe aus dem zum Bau benötigten Waren ist nicht mehr zu sehen, es tauchen aber wieder ein paar Einträge auf die in der alten Version nicht sichbar waren (sind aber nicht alle von den ausgeblendeten) 
![5](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/142307444/a4e1ca1c-3a98-4843-a20e-0a59975921e1)

**Comment by Achimobil** [comment]
Hmm... Ausgangslager voll. Das konnte ich nachvollziehen in meiner Produktion und die sind jetzt auch ausgeblendet, wenn es keine nicht ausgeblendete Linie gibt. Kannst hier testen ob jetzt alles gut ist: https://github.com/Achimobil/FS22_ProductionInfoHud/releases/tag/1.3.0.12

**Comment by Holger-70** [comment]
👍 so bei dem was ich alles getestet habe wurde mir nichts mehr falsch angezeigt. 
Achim sehr gute Arbeit vielen Dank
