### ISSUE TITLE
Schließt/Öffnet in x Minutenanzeigen, wenn OpenTime Script verfügbar

### ISSUE THREAD

**Issue by Akita83** [Achimobil/FS22_ProductionInfoHud#14]
Meine Idee und Wunsch wäre wenn man hinter die angegebenen Zeiten noch einfügen könnte als Text Produktion schließt in ... Minuten Basiered auf unser OpenTime Script was auf der Ackendorf von uns verbaut ist den Mod bekommt man auf unserer HP die du ja kennst.
Solltest du aber noch was benötigen weißt du ja wo du mich findest.
![20230830233228_1](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/78882145/30e18f23-3744-4296-b757-9483d42ac1ad)

**Comment by Achimobil** [comment]
Da das Skript mittlerweile von vielen Maps verwendet wird, schau ich mir auf jeden fall mal an, was da möglich wäre in der original und in der MOH Anzeige

**Comment by Achimobil** [comment]
Also die Karte hab ich noch hier liegen in der Version 1.7.
Aber welche Produktion hat so was und warum fehlen überall die Englischen Übersetzungen?

**Comment by Akita83** [comment]
Alle Produktionen sollten es haben wenn sie über das Farmland gekauft wurden und die Übersetzung fehlt weil es jemand für uns übersetzen wollte aber sich nicht gemeldet hat bis dato.

**Comment by Achimobil** [comment]
Also vielleicht bin ich ja blind, aber in der Map ist kein Skript OpenTime drin. Oder hab ich was übersehen?

Und 2. Frage die aber nichts damit zu tun hat: Warum habt ihr da immer noch das veraltete aPalletSilo Skript drin, aktualisiert ist das doch imRevamp enthalten, wenn man FS22_A_ProductionRevamp.RevampSilo benutzt als type

**Comment by Akita83** [comment]
Die Ackendorf ist nicht auf Revamp ausgelegt soweit ich das in erinnerung habe das wollten wir in der Ackendorf 2 machen diese haben wir aber auf den nächsten LS gelegt da wir jetzt alles selber zeichnen an Gebäude etc. Das Script muss nicht in der Map sein sondern der Mod im Ordner die Einträge sind in der Map also in den Produktionen zu machen. Das ist ein eigener Mod. LG Ansonsten schreib mir im DC wenn du Zeit hast dann können wir quatschen.

**Comment by Achimobil** [comment]
Da hab ich wohl was verpasst. Hast du noch einen link zum Mod, der fehlt mir dann wohl.

**Comment by Achimobil** [comment]
So, ich sehe die öffnungszeiten Anzeige jetzt im Produktoinsmenü. Soweit so gut.
Ich kann mir gut vorstellen in den PIH bei dem Namen der Produktion so was zu schreiben:

Wenn geschlossen und öffnet wieder um 10 bis 18 Uhr das nächste mal:
Produktionsname (10~)

Und wenn geöffnet
Produktionsname (~18)

So könnte man kurz sehen was ist geschlossen und wann öffnet es und auch was ist offen und wann schließt es.
Allerdings siehe ich aktuell nicht die möglichkeit dies aus dem productionPoint einfach aus zu lesen.
Ich benötige dafür auslesbar ob für das script offen ja oder nein und die nächste öffnungszeit+schließzeit.
Alternativ eine info im productionPoint wo der zu schreibende Text drin steht.
Ich will dies nicht alle 5 sekunden im Mod neu berechnen müssen und so, das verstehst du bestimmt.

Hier was möglich wäre
- Du füllst im Skript eine property productionPoint.votTimeInfo und füllst die mit der aktuellen Öffnungszeit "10-18". Wenn das da ist, dann schreibe ich es hinter den Namen in Klammern. Das müsste sich natürlich ändern, sobald die Zeiten sich ändern.
- Ich bekomme eine Beschreibung wie ich das auslesen kann. Ausgang ist wie gesagt der productionPoint. Ich kann alles auslesen was da drin steht. Aber ich habe nicht wirklich lust mich jetzt durch den Mod zu arbeiten und da alles zu analysieren und so.

**Comment by Akita83** [comment]
Ok ich kümmer mich drum , danke schon mal. ;)

**Comment by Achimobil** [comment]
productionPoint.votOpeningTime <--- table mit den öffnungszeiten  max 4 --> productionPoint.votOpeningTime[1].startTime=8 , productionPoint.votOpeningTime[1].endTime=10 
productionsPoint.votIsOpening <--- ist ein boolean wenn geöffnet dann true sonst false
productionsPoint.votOpeningTime ~= nil <--- ist es nil sind wir dort nicht aktiv oder vorhanden
und wenn revamp aktiv und in der production vorhanden dann ist der mod komplett raus aus der produktion

**Comment by Achimobil** [comment]
Jetzt kannst du testen:
https://github.com/Achimobil/FS22_ProductionInfoHud/releases/tag/1.3.0.10

**Comment by Akita83** [comment]
Servus Achim danke für die Testversion , ich habe diese im SP sowie auf dem Dedi gestestet die Syncronisation funktioniert wunderbar. Genau so habe ich es mir vorgestellt vielen Dank für deine Arbeit und Mühe. LG Timo ;)
