### ISSUE TITLE
Produkte die nur aufgrund von vorhandenem Booster in einer Produktion entstehen werden im PIH nicht angezeigt.

### ISSUE THREAD

**Issue by RolfB69** [Achimobil/FS22_ProductionInfoHud#15]
Als Beispiel dient die NF-Marsch mit dem Produktions-Pack. Dort gibt es Obstplantagen und Feldplantagen, welche Honig produzieren können wenn Bienenstöcke vorhanden sind. Die Bienenstöcke sind Booster, und der Honig ist als "outputConditional" bei diesen eingetragen. Vielleicht gibt es ja eine Möglichkeit auch solche Produkte im PIH abzufangen und anzuzeigen.

**Comment by Achimobil** [comment]
Und was möchtest du das da angezeigt wird?

**Comment by RolfB69** [comment]
In dem Beispiel wird der Honig nicht im PiH aufgeführt, und es wäre schön wenn dieser dort auch berücksichtigt würde. Entweder in der Kategorie kein Verbrauch oder im Umlauf, je nachdem ob man einen Verbraucher hat oder nicht. Aktuell wird in dem Beispiel der Honig "totgeschwiegen", also es sieht so aus als würde man gar keinen produzieren.

**Comment by Achimobil** [comment]
Ah, in der Liste von Verbrauch und Produktion. Schau ich mir an

**Comment by Achimobil** [comment]
Hier drin kannst du dir das selbst anschauen: https://github.com/Achimobil/FS22_ProductionInfoHud/releases/tag/1.3.0.8

**Comment by RolfB69** [comment]
Super, danke. Funktioniert wie ich es mir gewünscht habe.
