### ISSUE TITLE
Production Info HUD bleibt sichtbar, wenn HUD ausgeblendet

### ISSUE THREAD

**Issue by MeRida2104** [Achimobil/FS22_ProductionInfoHud#16]
Hi Achim,

es gibt ja die Möglichkeit das Game-HUD auszublenden (bspw. über die Console, [einen Mod ](https://www.farming-simulator.com/mod.php?lang=de&country=ch&mod_id=228087) oder über Easy Dev Controls. 

Mir ist aufgefallen, dass dein Production Info HUD sichtbar bleibt, auch wenn das Game-HUD ausgeblendet ist. Hier zwei Screenshots dazu:

Game-Hud an: 
![image](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/96819380/14357840-5eb4-464c-8448-7d9ffbe507b3)

Game-Hud aus:
![image](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/96819380/53502ba9-9f86-4bff-982f-31133703cad2)

Kannst du dir das mal ansehen? Danke :)

**Comment by Achimobil** [comment]
Schau ich mir mal an
