### ISSUE TITLE
Hud blendet nicht aus 

### ISSUE THREAD

**Issue by andremeyer123** [Achimobil/FS22_ProductionInfoHud#17]
Bei 2 Mods ist es jetzt aufgefallen

https://www.farming-simulator.com/mod.php?lang=en&country=be&mod_id=228087    hatte ja schon ein user im stream gesagt
https://www.farming-simulator.com/mod.php?lang=en&country=si&mod_id=224402    hab ich heute gesehen

**Comment by Achimobil** [comment]
https://github.com/Achimobil/FS22_ProductionInfoHud/releases/tag/1.3.0.14
