### ISSUE TITLE
Filltypes die auch Output sind werden nicht angezeigt und outputConditional von Boostern werden nicht berücksichtigt in der Zeitberechnung

### ISSUE THREAD

**Issue by TomEngelsdorf** [Achimobil/FS22_ProductionInfoHud#18]
Hi Achim,
Wir hatten schon mal kurz darüber gesprochen und ich habe mit Daniel auch gesprochen. Der hat ja mit Dir Kontakt aufegenommmen. Auf der NF habe wir das Problem wenn Input Filltypes wie leerpaletten auch Output filltypes sind in den Produktionen, dass wenn der Input level auf Null ist, das keine Meldung im Production Infohub erscheint und die Produktion steht.
Würde mich - und viele andere auch - freuen wenn wir dieses abstellen könnten. Gerne stehe ich auch für Test zur Verfügung.
LG
Tom

**Comment by Achimobil** [comment]
Ich werde mir das anschauen, aber wenn die als conditional output bei einem nicht booster eingetragen sind, dann ist das falsch eingetragen und werde ich nicht berechnen. Die gehören dann als normaler output eingetragen. Muss mir aber dann auch erst mal die neuster Version runter laden um es zu testen.

**Comment by Achimobil** [comment]
Schon mal geprüft. Ist alles falsch eingetragen in den Produktionen.
Conditional Outputs sind nur für Booster. Das heißt wenn ein Booster angeliefert wird, der ja nicht erforderlich ist, dann hat man einen zusätzlichen output. Hier wurde das aber bei nicht boostern eingetragen. Das muss in allen Produktionen angepasst werden. Wir werden überlegen in Revamp bei so einem Schwachsinn einen Fehler zu werfen im nächsten Update.

Zur verdeutlichung das hier ist falsch:
![image](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/65055783/4b460659-1220-4616-b95d-c67014e5e1c5)

So ist es richtig
![image](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/65055783/b4c828fd-8487-4ffc-9099-ce335395ae7c)

**Comment by Achimobil** [comment]
Aber es ist generell so, dass der PIH Inputs nur anzeigt, wenn sie nicht auch output sind und outputs nur anzeigt, wenn diese fast voll oder voll sind. Das werde ich hier mal prüfen ob es möglich wäre das zu berechnen. Dazu muss ich mir aber erst mal eine Produktion erstellen, die korrekt ist

**Comment by TomEngelsdorf** [comment]
Ok danke

Redest Fu oder ich mit Daniel ?

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Achim Kuntz ***@***.***>
Gesendet: Friday, December 1, 2023 8:28:51 AM
An: Achimobil/FS22_ProductionInfoHud ***@***.***>
Cc: TomEngelsdorf ***@***.***>; Author ***@***.***>
Betreff: Re: [Achimobil/FS22_ProductionInfoHud] Output Conditional (Issue #18)


Aber es ist generell so, dass der PIH Inputs nur anzeigt, wenn sie nicht auch output sind und outputs nur anzeigt, wenn diese fast voll oder voll sind. Das werde ich hier mal prüfen ob es möglich wäre das zu berechnen. Dazu muss ich mir aber erst mal eine Produktion erstellen, die korrekt ist

**Comment by Achimobil** [comment]
Vielleicht schickst du ihm einfach den link nach hier. ist ja jetzt beschrieben was da falsch ist in seinen produktionen und das kann er dann selbst lesen

**Comment by TomEngelsdorf** [comment]
Habe ihm email geschrieben mit deinem text

Von Outlook<http://aka.ms/weboutlook> gesendet.
Von: Achim Kuntz ***@***.***>
Gesendet: Freitag, 1. Dezember 2023 10:46
An: Achimobil/FS22_ProductionInfoHud ***@***.***>
Cc: TomEngelsdorf ***@***.***>; Author ***@***.***>
Betreff: Re: [Achimobil/FS22_ProductionInfoHud] Output Conditional (Issue #18)


Vielleicht schickst du ihm einfach den link nach hier. ist ja jetzt beschrieben was da falsch ist in seinen produktionen und das kann er dann selbst lesen

-

**Comment by Achimobil** [comment]
Generell hab ich für die nächste Testversion die anzeige von Inputs die auch Output sind mit eingebaut und auch die conditional outputs von boostern werden jetzt mit eingerechnet bei der Restzeit, wenn diese den bedarf verringern weil angeliefert. Letzteres wird bei der Marsch nichts bringen, weil die nicht bei Boostern eingetragen sind. kann dann in der nächsten Testversion getestet werden.

**Comment by Achimobil** [comment]
@TomEngelsdorf das die Leerpaletten generell angezeigt werden kannst du jetzt [hier](https://github.com/Achimobil/FS22_ProductionInfoHud/releases/tag/1.3.0.17) testen.

**Comment by TomEngelsdorf** [comment]
Server startet gerade neu


Von Outlook<http://aka.ms/weboutlook> gesendet.
Von: Achim Kuntz ***@***.***>
Gesendet: Freitag, 1. Dezember 2023 11:51
An: Achimobil/FS22_ProductionInfoHud ***@***.***>
Cc: TomEngelsdorf ***@***.***>; Mention ***@***.***>
Betreff: Re: [Achimobil/FS22_ProductionInfoHud] Filltypes die auch Output sind werden nicht angezeigt und outputConditional von Boostern werden nicht berücksichtigt in der Zeitberechnung (Issue #18)


@TomEngelsdorf<https://github.com/TomEngelsdorf> das die Leerpaletten generell angezeigt werden kannst du jetzt hier<https://github.com/Achimobil/FS22_ProductionInfoHud/releases/tag/1.3.0.17> testen.

-

**Comment by Achimobil** [comment]
@TomEngelsdorf Diese Comments hier sehen merkwürdig aus von dir.
Wenn du per Mail antwortest, dann bitte nicht den Text als reply drin lassen, danke

**Comment by TomEngelsdorf** [comment]
***@***.***

Geht - super Danke
