### ISSUE TITLE
Error Running LUA method "draw"

### ISSUE THREAD

**Issue by le-Vinyl** [Achimobil/FS22_ProductionInfoHud#21]
Guten Abend Achimobil. 
Mit dem Update von ProductionInfoHud auf Github erhalte ich im Mp diesen Fehler 
"Error: Running LUA method "draw" C:/ ....... mods/FS22_ProductionInfoHud/ProductionInfoHud.lua:1330 attempt to compare number with nil
Es werden auch 13 Fehler im Menü von Nirtado angezeigt

**Comment by Achimobil** [comment]
Dann stimmt da bei dir was nicht. Die Version läuft bei uns fehlerfrei. 
Anhand der Zeile kann ich nur empfehlen mal die Einstellungsdatei ProductionInfoHudSettings.xml im modSettings zu löschen (vorher sichern), die scheint fehlerhaft zu sein. Wenn das hilft, ticket bitte closen, wenn nicht, dann bitte vollständige log und die fehlerhafte Settingsdatei hier hochladen zur prüfung.
