### ISSUE TITLE
Erweiterungen werden nicht berücksichtigt

### ISSUE THREAD

**Issue by mdkder3** [Achimobil/FS22_ProductionInfoHud#23]
Habe hier etwas gefunden.
Es Handelt sich um die 500KW BGA mit einem Erweiterungs Mist Silo 
https://www.farming-simulator.com/mod.php?lang=de&country=be&mod_id=235197

Die Anzeige zeigt die ganze Zeit Leer an.
haben auch schon ohne Siloerweiterung versucht und auch andere
es wird immer leer angezeigt

![fsScreen_2024_02_06_08_01_07](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/157468288/efa10dfc-528c-48c9-ace9-68c8c8f6cb27)
![fsScreen_2024_02_06_08_00_58](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/157468288/23ba6449-dae2-4246-9302-7b198fd5bfbf)

**Comment by Achimobil** [comment]
Der Produktion Info Hud ließt die daten nur aus dem Storage der Produktion aus und kann nicht mit irgendeiner Art von Erweiterung arbeiten. Das ist vom design her so und das an zu passen wäre eine Komplette neu Programmierung dieses Teils der nicht geplant ist für del LS22. Grund hierfür ist, dass Lagererweiterungen für Lager gedacht sind und nicht für Produktionen. Das es da funktioniert ist ein Fehler vom LS und laut doku nicht gewollt. Deshalb wurde das von Anfang an nicht berücksichtigt.
Ich passe den Titel an und pack es auf die Wunschliste, für den Fall dass dieser Teil des Mods aufgrund eines Giants Patches doch mal neu gemacht werden muss, dann werde ich das berücksichtigen. 

Übrigens sind Misthaufenerweiterungen auch nicht für Silos sondern für Ställe die Mist machen. Auch diese dürften für Produktionen nicht funktionieren.

**Comment by mdkder3** [comment]
Das macht aber keinen Sinn !?!
weil alles andere aus der BGA wird richtig angezeigt!
Ich habe an der BGA eine Gülle Silo Erweiterung, da wird alles richtig angezeigt.

Und selbst wenn ich keine Silo Erweiterung für Mist an der BGA habe, wird das immer noch als Leer angezeigt, obwohl es voll ist.

**Comment by Achimobil** [comment]
Da diese Erweiterungen zwar nicht funktionieren sollten, aber wohl doch funktionieren hab ich mal versucht diese bei produktionen zu berücksichtigen. Bitte selbst testen und rückmelden ob alles geht wie erwartet.

https://github.com/Achimobil/FS22_ProductionInfoHud/releases/tag/1.4.0.4

**Comment by mdkder3** [comment]
Okay checke ich die Tage und melde mich 
Danke schon mal

**Comment by mdkder3** [comment]
Moin
sieht gut aus aber ist das richtig das MAX 3 Tage vorher angezeigt wird das es bald leer ist?
und besteht die Möglichkeit das LEER als ROT gezeigt wird? weil der Unterschied zwischen "Bald leer" und "LEER" ist farblich kaum zu erkennen manchmal
Gruß und Danke für die Mühe schonmal

**Comment by Achimobil** [comment]
Was hast du den für einen Mod? Bald leer und Leer gibts nicht. Es gibt eine Anzeige für Leer oder eine Restlaufanzeige.
Die Restlaufanzeige zeigt an sobald es weniger als 2 Monate Restlaufzeit sind und es weniger als 50% Füllstand sind.
Und der Unterschied zwischen mehr als 24 Stunden (weiß), weniger als 24 Stunden (orange) und leer (rot) ist schon deutlich erkennbar.

**Comment by mdkder3** [comment]
Moin 
sorry für die späte Rückmeldung.
bin aktuell viel unterwegs und komme leider nicht zum testen.
versuche das aber am kommenden Wochenende zu erledigen.
Gruß

**Comment by mdkder3** [comment]
Moin 
das kein MOD
das unter Silo Erweiterungen der Misthaufen Aufbau.
MOD habe ich noch nicht testen können.
versuche den MOD von oben demnächst zu testen.


Wegen der Farbe, wenn ich mir das (auch oben im Screenshot) anschaue ich das bei mir kein Rot, eher ein dunkles Orange

**Comment by mdkder3** [comment]
Moin 
der MOD von oben macht das auch wird auch akzeptiert aber ich glaube die BGA braucht einfach nicht so viel Mist wodurch ewig nix angezeigt wird.

Gruß

**Comment by mdkder3** [comment]
![1](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/157468288/1823c391-ad10-4aee-8d45-62e79a6a072f)
![2](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/157468288/6b1ddaf4-0d06-44fa-b599-371a973a690e)
![3](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/157468288/341f7a1b-b1b5-4ca9-b67b-6ec2ffcbbbbf)


anbei nochmal einige Screenshoots
und ich finde LEER könnte sich deutlicher abheben z.b. wie VOLL, das hebt sich schön ab.

**Comment by Achimobil** [comment]
Naja, es ist Orange, dunkel orange und rot. Deutlicher wäre es nur wenn man Geld als erstes nutzen würde, das sieht man aber kaum wenn es hell. Deshalb hab ich die Farben ja so gewählt wie sie sind. Sind die besten und auf einem Normalen Monitor ohne schnickschnack auch gut unterscheidbar.
Eine Misthaufenerweiterung ist keine Lagererweiterung. Diese kann ich nicht performant auslesen und berücksichtigen.

**Comment by Achimobil** [comment]
so, mehr als ich jetzt an den Farben gemacht habe ist nicht notwendig. das gelb etwas gelber halt, dass man es besser von dem Orange und Rot unterscheiden kann. Erweiterungen werden ja jetzt berücksichtigt, weshalb ich das hier schließe
