### ISSUE TITLE
Farm Production Pack Lua Error

### ISSUE THREAD

**Issue by johnwayne1930** [Achimobil/FS22_ProductionInfoHud#25]
[log_PID2.txt](https://github.com/Achimobil/FS22_ProductionInfoHud/files/15370563/log_PID2.txt)

Ich habe nach dem rumspielen mit dem Farm Production Pack DLC bemerkt das sich InfoHud Lua Error in die Log eingeschlichen haben.
Die Anzeige zeigte außerdem immer "Alle Produktionen versogt" und "Nichts zu verkaufen" an.
Aus dem Farm Production Pack hatte ich die Lely Sphere gebaut und aktiv, nach dem ich das ding verkauft hab hörten die Error in der Log auf und die PID-Anzeige hat wieder Infos angezeigt.

Sorry falls das schon bekannt ist, hab auf die schnelle im Discord und hier nichts gefunden.
Beste Grüße.

**Comment by Achimobil** [comment]
Nein, bisher ist nichts bekannt, aber du hast auch lua fehler vorher schon drin. Getestet mit nur Map und PIH im Mods ordner?

**Comment by johnwayne1930** [comment]
Gerne hier nochmal mit so gut wie nur PID im Ordner. 
[log_PID3.txt](https://github.com/Achimobil/FS22_ProductionInfoHud/files/15376134/log_PID3.txt)

Sobald ich die Lely Sphere aktiviere fangen die Lua Error an, bis zur deaktivierung besagter Produktion.

![fsScreen_2024_05_20_12_50_01](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/7887254/dc4137bb-2a5c-47d1-845c-f5e2075f8bd9)

**Comment by Achimobil** [comment]
Da müsste der Modder ran und mal die benötigten Daten eintragen die Giants eigentlich immer will, aber da die sich erfahrungsgemäß nicht bewegen schaue ich mir das an, wenn ich wieder modde. Aktuell hab ich keine Zeit dazu.
Ich mir nicht aufgefallen, weil ich das fehlerhafte Pack selbst nicht nutze und ich weiß auch nicht ob ich es testen kann.

**Comment by Achimobil** [comment]
https://github.com/Achimobil/FS22_ProductionInfoHud/releases/tag/1.4.0.6
