### ISSUE TITLE
[Feature Request] separation of thousands

### ISSUE THREAD

**Issue by Antaiir** [Achimobil/FS22_ProductionInfoHud#26]
Hi there,

it would be great to have the displayed numbers with a separation of thousands.

For many people, like poor old me, longer numbers are way better to read, when there is a separation. 

Maybe with config options for enable oder disable it, and a choice between dot or comma for localization?

Thank you! :-)

**Comment by Achimobil** [comment]
Could you add a sceen shot what you mean exactly?

**Comment by Achimobil** [comment]
After so long no answer I close the ticket. Without information not solvalble
