### ISSUE TITLE
Mixgruppen werden nicht mehr angezeigt 

### ISSUE THREAD

**Issue by Koenigsboa** [Achimobil/FS22_ProductionInfoHud#29]
Hallo Achim
Ich habe das Problem, das Mixgruppen nicht mehr angezeigt/ berechnet werden. Die bilder sind von der Backerei auf der Marsch aber ich habe auch eine eigene Produktion getestet und da funktioniert es auch nicht. 

![fsScreen_2024_08_27_21_24_59](https://github.com/user-attachments/assets/9cf08a07-b2a3-4a6c-be00-61cabd17fd69)
![fsScreen_2024_08_27_21_25_33](https://github.com/user-attachments/assets/26faa18d-e1a9-4805-9998-dc8f4bbcda9b)
![fsScreen_2024_08_27_21_25_09](https://github.com/user-attachments/assets/46ac55a2-edf5-4bc6-804a-94e79505a8b6)
[log.txt](https://github.com/user-attachments/files/16767973/log.txt)

**Comment by Koenigsboa** [comment]
Ich habe gerade gesehen, das es schon ein Update gibt. Ich hatte nur im Discord nach der aktuellen Version gesucht und nicht hier.

**Comment by Achimobil** [comment]
kein ding, in der https://github.com/Achimobil/FS22_ProductionInfoHud/releases/tag/1.4.1.11 ist das behoben, falls das hier jemand findet brauch er nicht suchen ;)
