### ISSUE TITLE
Volle Tiere pro Art auswählen können

### ISSUE THREAD

**Issue by Achimobil** [Achimobil/FS22_ProductionInfoHud#3]

**Comment by Nexuspara** [comment]
Wie auf Forbidden Mods schon geschrieben, hier ein Wunsch für die Liste bzw. eine Anmerkung zu einer “geplanten” Funktion.
Eine Funktion einzelne volle Ställe in der Auflistung auszublenden wäre auch schön. Ich weiß leider nicht ganz, wie es pro Art gemeint ist, denn zB: Man hat 2 Hühnerställe. 1er für Eier, der ist natürlich Voll. Der 2te zweiter ist für Nachzucht und Mast für den Schlachter da. Somit wird ja immer der für die Eier als voll angezeigt und es wird ja auch keine Reproduktion in diesem Stall erwünscht. Bei einer Einteilung pro Art würde ich ja die Rasse Huhn blockieren und keine Benachrichtigung erhalten, wenn der Maststall voll ist. Es muss halt möglich sein, einen Stall im Tiermenü auszuwählen, weil das ja aktuell nicht der Fall ist. Man kann halt nur eine Tiergruppe auswählen. Ist halt zu erklären auch etwas schwer, aber ich glaube du weißt was ich meine.

**Comment by Achimobil** [comment]
Hab ich verstanden und ist auch schlüssig für mich, dass es pro Tierart nicht so gut wäre. 
Wenn ich mich da ran setze schaue ich ob ich pro Stall da was machen kann.
Danke fürs mit denken.

**Comment by Achimobil** [comment]
In der nächsten Version wird es so sein, dass wenn das Enhanced Animal genutzt wird und die Überbelegung eines Stalls wird zugelassen, dann wird dieser Volle stall nicht mehr angezeigt. Nur wenn er überbelegt ist, weil dann die Tiere Gesundheit verlieren, Somit brauche ich hier nicht umständlich was zu bauen, damit einzelne Ställe ignoriert werden können.
