### ISSUE TITLE
Fehler in Zusammenhang mit dem GEA-Stall auf der IIT3

### ISSUE THREAD

**Issue by Tidde23** [Achimobil/FS22_ProductionInfoHud#30]
Wenn der GEA-Stall platziert wird, Tiere gekauft werden, dann schmeißt das ProductionInfoHud Luas in der Log und es werden im InfoHud keine Informationen zu den Füllständen angezeigt
Der Stall wurde auf einem neuen Spielstand mit nur den benötigten Mods gestartet, so wie der Log auch entnommen werden kann.

[log.txt](https://github.com/user-attachments/files/17178625/log.txt)

**Comment by Achimobil** [comment]
Kannst du mal schauen, bei mir hat der fix funktioniert den ich nachstellen konnte

https://github.com/Achimobil/FS22_ProductionInfoHud/releases/tag/1.5.0.1

**Comment by Tidde23** [comment]
funktioniert. Vielen Dank :)

**Comment by Achimobil** [comment]
Version 1.5.1.0 ist als Update im ModHub eingereicht
