### ISSUE TITLE
Info data table pause menu

### ISSUE THREAD

**Issue by Vanquish081** [Achimobil/FS22_ProductionInfoHud#6]
Hello, I would like translate to ES, but I don't understand good the info in the data table...

What does it mean or want to indicate in each column?

**Comment by Achimobil** [comment]
![image](https://user-images.githubusercontent.com/65055783/236217539-bcb73fe4-e438-4e85-b481-57dfc3a1545a.png)
you mean wht tha columns in here means?

**Comment by Achimobil** [comment]
closing after 4 weeks of waiting

**Comment by Vanquish081** [comment]
wow... 4 weeks ... I'm sorry...
If you allow me to return to the subject, I would like to help with a correct translation.
What and how do you want to show in this table?
What I know...
Sell direct...
stores...
consume...
I personally don't quite understand the table.

**Comment by Achimobil** [comment]
In my regular work as a programmer I am used to get answers to questions within hours and days are rather the exception. Unfortunately, I always forget that the clocks in the LS go much slower, if you consider the error messages at giants of me sometimes already 14 months waiting for processing. ;)
I did not want to offend you or so. I put the ticket on open again. I thought you could do that also or not?

Ofcourse we can talk over the topic and I am glad that you wanna help with a better translation.
So you mean this Table from the screen. Let expain this on the easiest way I can think of ;)

A production has 3 settings on the outgoing products. These are the first 3 columns there.
For a production you need products as input. that is the 4th column,
These four columns are in the time range shown which is in the top of the list. In my example that is per year.
The last column is only filled when the screen is set to year and then it shows how many hectar of field you need to put a crop on to harvest as many as you need for column 4, but without taking bonus for the field. Bonus means things like lime or fertilizer.

To get the columns in one list. And it is always the summary of all your productions.

1. Amount of output products per year set to direct sell in the productions
2. Amount of output products per year set to keep in the productions
3. Amount of output products per year set to distribute in the productions
4. Amount of input products per in the productions
5. Hector need to be harvested for the amount you need in column 4

Makes that sense for you?

**Comment by Vanquish081** [comment]
Let's see if I understand...

Will each column show the amount that has been Sold, stored or distributed throughout the year?

Column 4 shows the total that has been consumed for the sum of the previous 3 columns?

And in the last column, the area that needs to be worked to obtain what is consumed in column 4?

In other words, statistical data, such as the balance of bank expenses.

I don't think I understand the "times" of each column, if I understood correctly, the first 3 columns are accumulated data, the 4th column is based on the data of these 3 columns and the surface column is the useful one, that is, the we need to know how much to sow.

![fsScreen_2023_06_09_09_57_27](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/12070061/aab28525-79d9-4068-8685-4a779cde2be0)

![fsScreen_2023_06_09_09_59_00](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/12070061/4de75811-2a92-41d9-9432-d541733592f7)

![fsScreen_2023_06_09_09_59_05](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/12070061/af11daad-1e20-44c5-a7c8-75864b8df89f)

Juice Cellar need 7.704 lts. of grapes per month?

Note: I'm really sorry for not answering sooner, I forgot the notice received by e-mail, I'm really sorry.

**Comment by Achimobil** [comment]
No problem for late reply, But good that i close it so now we are in contact again ;)

The values are not what has been happend. It are the current amounts.
So the first three columns are the amount which is products from the activated productions and if they are distributed, keeped or sold directly.
The forth is for input amount and you are right, your products needs 7704 liter per month.
It produce 2,3 liter juice pre cycle which will be 5906,4 liter per month.
Ever production has different cycles and so you can directly see what is needed per mpnth and what is products per month
When you now have a production which produce grapes with a rate of 24 per cycle and 363 cycles per month which will be 8712 per month and you set this on Dirstribute you will see this in the line of the Grapes in the distribute column. So you know that you dirstibute more than you need for the juice production.

**Comment by Vanquish081** [comment]
well... another thing... **No Consumption** refers to the final products or those that are not used in other factories?
**No production** is the raw material?
and **circulation**...what do you want to refer to?

**Comment by Achimobil** [comment]
The thre blocks means the following
Circulation means that you produce a product and you consume a product. There you can see if you produce enaugh "middle" products in a longer production line
No production means that these products are neede for productions as input but you have no production of it. so you have to by or harvest these goods.
No consumption means that you only producing these but no production needs them. All these products are for selling only.

**Comment by Vanquish081** [comment]
Ok, this afternoon I can ready a translation to ES :)

Thanks for your time.

Edit:

[location_ES.zip](https://github.com/Achimobil/FS22_ProductionInfoHud/files/11714617/location_ES.zip)

attach file for location ES, I can't create new file in the translation folder, I don't know why.

Where is this line? I can't see it...
![Screenshot_1](https://github.com/Achimobil/FS22_ProductionInfoHud/assets/12070061/6d02b8fa-17b1-42f4-b5aa-2dd030d3232d)

**Comment by Achimobil** [comment]
Thanks for the ES translations. Would be nice when you also have a eye on future version, because I will only add new things in English for the languages I do not speak.

The head line in the list is currently not translatable.
